Backend news 1
wolox-training/ea-android pull request #11
Opened 2021-04-06 19:00 UTC by ErikEmmanuelAnrique

### **SUMMARY**
News are now obtained from the backend server.
Added error messages on bad response and connection error.

### **SCREENSHOTS**
![Screenshot_1617735250](https://user-images.githubusercontent.com/80703924/113764168-fd3ec980-96f0-11eb-9365-0206100df4d8.png)
![Screenshot_1617735268](https://user-images.githubusercontent.com/80703924/113764173-ff088d00-96f0-11eb-9e92-927822a68867.png)

### **TRELLO CARD**
https://trello.com/c/RLrTZNAy/11-u5-home-page-backend-news

2021-04-06 21:49 UTC, jcruz-wolox requested changes
I have any comments...

2021-04-06 21:49 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/BootstrapApplication.kt
> +
Remove empty line

2021-04-06 21:49 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/BootstrapApplication.kt
> +    private fun headersInterceptor() = Interceptor { chain ->
Good job!!

2021-04-06 21:49 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/network/repository/NewsRepository.kt
> +        if (page != null) {
you could do this check using let function:

`page?.let{
    NetworkRequestHandler.safeApiCall { services.getNewsPage(page) }
 }?: NetworkRequestHandler.safeApiCall { services.getFirstPage() }`

2021-04-06 21:49 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/EndlessRecyclerViewScrollListener.kt
> +
Remove empty line

2021-04-06 21:49 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/NewsPresenter.kt
> +    private val visibleThreshold = 5
We add all constant like this in the companion object

2021-04-06 21:49 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/NewsViewHolder.kt
> +    // Context is required by Glide
Remove comment

2021-04-06 21:49 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/NewsViewHolder.kt
> +            // Glide.with(context).clear(viewImage)
Here too

2021-04-07 12:40 UTC, ffasitella requested changes
Left some comments! Good job!

2021-04-07 12:40 UTC, ffasitella commented on app/build.gradle
> +    implementation 'androidx.room:room-runtime:2.2.5'
You are not using Room, so you don't need this dependence

2021-04-07 12:40 UTC, ffasitella commented on app/build.gradle
> +    implementation "androidx.paging:paging-rxjava2-ktx:$paging_version"
I think you are not using this dependency too

2021-04-07 12:40 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/network/repository/NewsRepository.kt
> +        page?.let { NetworkRequestHandler.safeApiCall { services.getNewsPage(page) } } ?: NetworkRequestHandler.safeApiCall { services.getFirstPage() }
You can set a default value for page instead of using this elvis operator. Something like `suspend fun getNewsList(page: Int? = 1)`

2021-04-07 12:40 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/NewsViewHolder.kt
> +    @SuppressLint("NewApi")
Remove this annotation

2021-04-07 12:40 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/NewsViewHolder.kt
> +    @SuppressLint("NewApi")
This too

2021-04-07 12:40 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/NewsViewHolder.kt
> +}
You can use PrettyTime to avoid doing this manually

2021-04-07 14:08 UTC, ffasitella approved these changes
Excellent job! 
One more task and we are ready! 🚀

2021-04-07 14:09 UTC, merged