News details frontend backend
wolox-training/ea-android pull request #12
Opened 2021-04-13 13:41 UTC by ErikEmmanuelAnrique

### **SUMMARY**

Created activity for News Details.
Added put/remove like function.
News feed is now sorted last like updates.

### **SCREENSHOTS**

![Screenshot_1618320967](https://user-images.githubusercontent.com/80703924/114561903-64560400-9c44-11eb-97c6-f9da4e1271dc.png)
![Screenshot_1618320973](https://user-images.githubusercontent.com/80703924/114561912-65873100-9c44-11eb-8312-65401a67bd94.png)
![Screenshot_1618320979](https://user-images.githubusercontent.com/80703924/114561915-66b85e00-9c44-11eb-8f1a-2403253a0582.png)

### **TRELLO CARD**

https://trello.com/c/W5zxF8Dk/8-u6-frontend-and-backend-news-detail

2021-04-13 18:18 UTC, ffasitella requested changes
Good one! Some issues to solve before merging.

2021-04-13 18:18 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/auth/login/LoginPresenter.kt
> +        }
here you can use somethin like `userSession.let { }` to avoid repeating it

2021-04-13 18:18 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/NewsViewHolder.kt
> +            viewLikeButton.isChecked = userId in likes
Nice!

2021-04-13 18:18 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/NewsViewHolder.kt
> +            viewTime.text = deltaTime(created_at)
I don't like having a function declared in a random file. I suggest to move this function to a String extension function. What do you think?

2021-04-13 18:18 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/details/NewsDetailsActivity.kt
> +            intent.getBooleanExtra(LIKES, false)
You can pass the entire New model as a Serializable here instead of passing every field separate

2021-04-13 18:18 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/details/NewsDetailsActivity.kt
> +                }
`putExtra(KEY_NEW, dataSet)`

2021-04-13 18:18 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/details/NewsDetailsFragment.kt
> +        Toast.makeText(requireContext(), getString(R.string.connection_call_error), Toast.LENGTH_SHORT)
You can use ToastFactory here and in the rest of the file

2021-04-13 18:18 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/features/homepage/news/details/NewsDetailsPresenter.kt
> +                    onResponseSuccessful { }
👀

2021-04-13 18:18 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/models/User.kt
> +data class User(val `data`: Data)
you can just declare this as `val data: Data`

2021-04-14 12:35 UTC, ffasitella approved these changes
Excellent job!! 🥇 👏🏽

2021-04-14 12:41 UTC, jcruz-wolox approved these changes
Congratulations Erik!

2021-04-14 12:43 UTC, merged