Login frontend 2
wolox-training/ea-android pull request #2
Opened 2021-03-22 17:33 UTC by ErikEmmanuelAnrique

### **Summary**

Implemented basic validation for user data. Main Activity changed from _LoginActivity_ to _RootActivity_.

### **Screenshots**

![Screenshot_1616433850](https://user-images.githubusercontent.com/80703924/112032540-456bc280-8b1b-11eb-89f5-a3800d1384a4.png)

### **Trello Card**

https://trello.com/c/ZAAmG3I4/17-u1-frontend-login-validaciones

2021-03-22 19:22 UTC, ffasitella requested changes
Wow! Amazing job!!
Just some little changes and we are ready to go! 🚀

2021-03-22 19:22 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/login/LoginPresenter.kt
> +    }
Move this private function to the bottom of the file

2021-03-22 19:22 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/login/LoginPresenter.kt
> +    }
We usually prefer to have curly brackets in the if/else statements, even if they are a single line. Like:
```
if (email.isEmpty()) {
    totalErrors.add(Errors.EMPTY_EMAIL)
}
```

2021-03-22 19:22 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/login/utils/Errors.kt
> +    abstract fun callAction(view: LoginView)
I would make `view` nullable. Like `view: LoginView?`

2021-03-22 19:58 UTC, jcruz-wolox approved these changes
If the Fede's changes are implemented, this PR is approved for me.
Good job!

2021-03-23 12:30 UTC, ffasitella approved these changes
Good job! 👍🏽

2021-03-23 12:38 UTC, merged